default: &default
  adapter:   mysql2
  encoding:  utf8mb4
  charset:   utf8mb4
  collation: utf8mb4_general_ci
  pool:      5
  socket:    /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: <%= ENV['database_name'] %>
  host:     <%= ENV['master_database_host'] %>
  port:     <%= ENV['database_port'] %>
  username: <%= ENV['database_username'] %>
  password: <%= ENV['database_password'] %>

production:
  <<: *default
  database: <%= ENV['database_name'] %>
  host:     <%= ENV['master_database_host'] %>
  port:     <%= ENV['database_port'] %>
  username: <%= ENV['database_username'] %>
  password: <%= ENV['database_password'] %>

test:
  <<: *default
  database: <%= ENV['database_name'] %>
  host:     <%= ENV['master_database_host'] %>
  port:     <%= ENV['database_port'] %>
  username: <%= ENV['database_username'] %>
  password: <%= ENV['database_password'] %>
