AllCops:
  Exclude: 
    - 'bin/*'
    - 'config/initializers/backtrace_silencers.rb'
    - 'config/environments/*'
    - 'config/routes.rb'
    - 'vendor/**/*'
  RunRailsCops: true

Style/Tab:
  Enabled: false

Style/IndentationWidth:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false
