source 'https://rubygems.org'

gem 'rails',           '4.2.5'
gem 'figaro',          '~> 1.1.1'
gem 'mysql2'
gem 'jbuilder',        '~> 2.0'
gem 'pry-rails',       '~> 0.3.3'
gem 'bcrypt',          '~> 3.1.10'
gem 'activeuuid',      '~> 0.6.1'
gem 'seedbank'
gem 'squeel'
gem 'redis',           '~> 3.2.1'
gem 'redis-namespace', '~> 1.5.1'
gem 'redis-rails',     '~> 4.0.0'
gem 'sidekiq',         '~> 4.0.0'

group :production do
  gem 'puma', '~> 2.15.3'
end

group :development, :test do
  gem 'pry-byebug'
  gem 'rails_best_practices'
  gem 'rubocop', require: false
  gem 'brakeman'
end

group :development do
  gem 'spring'
end

group :test do
  gem 'rspec-rails',        '~> 3.4.0'
  gem 'factory_girl_rails', '~> 4.5.0'
  gem 'database_cleaner',   '~> 1.5.1'
  gem 'json_spec',          '~> 1.1.4'
end
